### ISSUE TITLE
Generate classes that currently manual

### ISSUE THREAD

**Issue by EPashkin** [gtk-rs/gdk#143]
Seems most gdk classes that currently done manual way can be generated now, it add signals support.
Also better generate Monitor and possibly Sink to have full Gdk screen management.

**Comment by GuillaumeGomez** [comment]
That'd be awesome!

**Comment by lukasstevens** [comment]
I don't know if I should open a new issue for this, but I have a question concerning `Screen`, `Display` and `Monitor` which were updated/added with this pull request. As @EPashkin mentioned `Monitor` is now available. The problem is that the `Display` struct does not implement the corresponding method `get_monitor`. Therefore it is currently not possible to use the `Monitor` struct at all if I am not mistaken. Using the `Monitor` would be more ergomic and additionally using numbers to identify monitors is deprecated since 3.22.

**Comment by GuillaumeGomez** [comment]
It appeared in 3.22 so we should have it normally.

https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-monitor

**Comment by lukasstevens** [comment]
Sorry that I bothered you, I failed to specify the feature set in the Cargo.toml.

**Comment by EPashkin** [comment]
Also you can look https://github.com/gtk-rs/gdk/issues/146 if you don't have 3.22
